services:
  frontend:
    image: frontend
    ports:
      - 4200:80
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
  backend:
    image: backend
    restart: on-failure
    ports:
      - "4040:4040"
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
volumes:
  mysqldb-data:  # Define a volume for MySQL data
