apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-pv
spec:
  capacity:
    storage: 4Gi  # Adjust this to your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  # For demonstration purposes only; don't use in production!
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # Adjust this to your needs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: ecommerce
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mysqldb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysqldb-data
          persistentVolumeClaim:
            claimName: mysqldb-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30002 # port forward to 30002
  selector:
    app: database